name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload static files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'github-pages'
          path: dist/
          retention-days: 1
