name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.40.0-jammy
    env:
      TestsLocation: tests/UiTests
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - run: dotnet build
        working-directory: $TestsLocation

      - name: Run your tests
        run: dotnet test
        working-directory: $TestsLocation
        env:
          HOME: /root