name: Playwright Tests
on:
  workflow_dispatch:
  deployment_status:

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/dotnet:v1.40.0-jammy
    env:
      Tests_Location: tests/UiTests
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - run: dotnet build
        working-directory: ${{ env.Tests_Location }}

      - name: Run your tests
        run: dotnet test
        working-directory: ${{ env.Tests_Location }}
        env:
          HOME: /root
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
